In [1]:
#21
def sum(num1, num2):
    return num1 + num2


n1 = float(input('请输入一个自然数：'))
n2 = float(input('请输入另一个自然数：'))

print('求和结果为：', sum(n1, n2))


求和结果为： 7.0


In [2]:
#22
import math


def showPower(n):
    return math.pow(2, n)


num = int(input('请输入想查看2的几次方：'))
print('结果为', showPower(num))




结果为 16.0


In [3]:
#23
def getFactor(num):
    arr = []
    for i in range(1, num):
        if num % i == 0:
            arr.append(i)
    return arr


num = int(input('请输入一个数：'))

print('它可以被', getFactor(num), '整除')


它可以被 [1, 2, 3, 4, 6] 整除


In [4]:
#24
num = int(input('请输入一个数字：'))

print('二进制结果为：', bin(num))
print('八进制结果为：', oct(num))
print('十六进制结果为：', hex(num))



二进制结果为： 0b1010
八进制结果为： 0o12
十六进制结果为： 0xa


In [5]:
#25
def findAscii(n):
    return ord(n)


print('该字符的ASCII值为：', findAscii(input('请输入一个字符：')))



该字符的ASCII值为： 65


In [6]:
#26
def gcd(a, b):
    if a % b == 0:
        return b
    else:
        return gcd(b, a % b)


n, m = input('请输入两个数').split(' ')

print(gcd(int(n), int(m)))



1


In [7]:
#27
def gcd(a, b):
    if a % b == 0:
        return b
    else:
        return gcd(b, a % b)


def lcm(a, b):
    return a * b / gcd(a, b)


n, m = input('请输入两个数').split(' ')

print(lcm(int(n), int(m)))



12.0


In [8]:
#28
def getFactor(num):
    arr = []
    for i in range(1, num):
        if num % i == 0:
            arr.append(i)
    return arr


num = int(input('请输入一个数：'))

print('因子为', getFactor(num))


因子为 [1, 2, 3, 4, 6]


In [9]:
#29
import re


def add(a, b):
    return a + b


def sub(a, b):
    return a - b


def mul(a, b):
    return a * b


def div(a, b):
    return a / b


def cal(flag, a, b):
    if re.match('add', flag):
        return add(a, b)
    elif re.match('sub', flag):
        return sub(a, b)
    elif re.match('mul', flag):
        return mul(a, b)
    elif re.match('div', flag):
        return div(a, b)
    else:
        return 'err'


operation = input('请输入操作码（add, sub, mul, div）:')
n, m = input('请输入两个数').split(' ')
print('计算结果为：', cal(operation, int(n), int(m)))



计算结果为： 12


In [10]:
#30
import random
import operator


def getPokers():
    pokers = []
    poker = []
    for i in ['♥', '♠', '♦', '♣']:
        for j in ['A', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K']:
            poker.append(i)
            poker.append(j)
            pokers.append(poker)
            poker = []
    return pokers


pokers = getPokers()
random.shuffle(pokers)  # 将序列的所有元素随机排序
li = {}
for player in ['player1', 'player2', 'player3', 'player4']:
    b = random.sample(pokers, 13)
    for s in b:
        pokers.remove(s)
    li.setdefault(player, b)

print('player1：', sorted(li['player1'], key=operator.itemgetter(0, 1)))  # operator.itemgetter(0, 1)根据花色和数字来排序
print('player2：', sorted(li['player2'], key=operator.itemgetter(0, 1)))
print('player3：', sorted(li['player3'], key=operator.itemgetter(0, 1)))
print('player4：', sorted(li['player4'], key=operator.itemgetter(0, 1)))



player1： [['♠', '4'], ['♠', '8'], ['♠', 'Q'], ['♣', '5'], ['♣', '9'], ['♣', 'A'], ['♥', '10'], ['♥', '8'], ['♥', '9'], ['♦', '5'], ['♦', '6'], ['♦', '9'], ['♦', 'A']]
player2： [['♠', '6'], ['♣', '10'], ['♣', '3'], ['♣', '6'], ['♣', '7'], ['♣', 'Q'], ['♥', '6'], ['♥', '7'], ['♥', 'A'], ['♥', 'Q'], ['♦', '2'], ['♦', '3'], ['♦', '4']]
player3： [['♠', '3'], ['♠', 'A'], ['♣', '2'], ['♣', '8'], ['♣', 'K'], ['♥', '4'], ['♥', '5'], ['♥', 'J'], ['♥', 'K'], ['♦', '10'], ['♦', '7'], ['♦', '8'], ['♦', 'K']]
player4： [['♠', '10'], ['♠', '2'], ['♠', '5'], ['♠', '7'], ['♠', '9'], ['♠', 'J'], ['♠', 'K'], ['♣', '4'], ['♣', 'J'], ['♥', '2'], ['♥', '3'], ['♦', 'J'], ['♦', 'Q']]


In [11]:
#31
import calendar
# 设置第一天是星期天
calendar.setfirstweekday(firstweekday=6)

n = int(input('请输入所查看日历的级别 1（输出全年），2（输出某月）：'))

if n == 1:
    yy = int(input("输入年份: "))
    cal = calendar.TextCalendar()
    cal.pryear(yy)

if n == 2:
    yy = int(input("输入年份: "))
    mm = int(input("输入月份: "))
    print(calendar.month(yy, mm))


                                  2017

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
                   1             1  2  3  4  5             1  2  3  4  5
 2  3  4  5  6  7  8       6  7  8  9 10 11 12       6  7  8  9 10 11 12
 9 10 11 12 13 14 15      13 14 15 16 17 18 19      13 14 15 16 17 18 19
16 17 18 19 20 21 22      20 21 22 23 24 25 26      20 21 22 23 24 25 26
23 24 25 26 27 28 29      27 28                     27 28 29 30 31
30 31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
                1  2       1  2  3  4  5  6  7                1  2  3  4
 3  4  5  6  7  8  9       8  9 10 11 12 13 14       5  6  7  8  9 10 11
10 11 12 13 14 15 16      15 16 17 18 19 20 21      12 13 14 15 16 17 18
17 18 19 20 21 22 23      22 23 24 25 26 27 28      19 20 21 22 23 24 25
24 25 26 27 28 29 30      

In [12]:
#32
def Fibonacci(n):
    if n <= 2:
        return 1
    else:
        return Fibonacci(n - 1) + Fibonacci(n - 2)


n = int(input("输入一个正整数n，n为输出项数:"))
for i in range(1, n + 1):
    print(Fibonacci(i), end=' ')



1 1 2 3 5 8 13 21 34 55 

In [13]:
#33
def sum(n):
    if n == 1:
        return 1
    else:
        return sum(n - 1) + n


i = int(input('输入一个整数：'))
print('其整数之和为：', (sum(i)))



其整数之和为： 55


In [14]:
#34
def Factorial(n):
    if n == 0:
        return 1
    else:
        return n * Factorial(n - 1)


i = int(input('输入一个整数：'))
print(i, '的阶乘为', Factorial(i))



5 的阶乘为 120


In [15]:
#35
def dec2bin(n):
    result = "0"
    if n == 0:
        return result
    else:
        result = dec2bin(n // 2)
        return result + str(n % 2)


n = int(input("请输入一个十进制的数字："))
print(dec2bin(n))



01010


In [16]:
#36
import numpy

A = numpy.mat('1,2;3,4')
B = numpy.array([[3, 2], [3, 4], [9, 6]])
print(A)
print('')
print(B)



[[1 2]
 [3 4]]

[[3 2]
 [3 4]
 [9 6]]


In [17]:
#37
import numpy

A = numpy.array([[3, 2], [3, 4], [9, 6]])
print(A)
print('')
print(A.T)



[[3 2]
 [3 4]
 [9 6]]

[[3 3 9]
 [2 4 6]]


In [18]:
#38
import numpy

A = numpy.array([[3, 2], [3, 4], [9, 6]])
B = numpy.array([[3, 1, 2], [3, 6, 4]])
C = numpy.dot(A, B)
print("A:\n", A)
print("B:\n", B)
print("A×B:\n", C)



A:
 [[3 2]
 [3 4]
 [9 6]]
B:
 [[3 1 2]
 [3 6 4]]
A×B:
 [[15 15 14]
 [21 27 22]
 [45 45 42]]


In [19]:
#39
s = input("输入一个字符串:")
d = ''.join(reversed(s))
print(d)
if s == d:
    print("字符串是回文")
else:
    print("字符串不是回文")



abcba
字符串是回文


In [20]:
#40
import string

i = input("输入一条带标点的字符串(英文标点)：")
print("".join(i.split('.')))



adfjkdffgdkfjk


In [21]:
#41
list = ["delphi", "java", "python", "python", "c++", "c", "golang"]

list.sort(reverse=False)  # 按降序排列

print(list)



['c', 'c++', 'delphi', 'golang', 'java', 'python', 'python']


In [22]:
#42
set1 = set([1, 2, 3, 4, 5])
set2 = set([0, 2, 3, 6, 7])

print('交集', set1 & set2)
print('并集', set1 | set2)
print('差集', set1 - set2)



交集 {2, 3}
并集 {0, 1, 2, 3, 4, 5, 6, 7}
差集 {1, 4, 5}


In [2]:
#43
str1 = input('请输入一个字符串')

strList = list(str1)
a = 0
e = 0
i = 0
o = 0
u = 0

for n in range(0, len(str1)):
    if strList[n] == 'a':
        a = a + 1
    elif strList[n] == 'e':
        e = e + 1
    elif strList[n] == 'i':
        i = i + 1
    elif strList[n] == 'o':
        o = o + 1
    elif strList[n] == 'u':
        u = u + 1

print('a:', a, 'e:', e, 'i:', i, 'o:', o, 'u:', u)


a: 1 e: 1 i: 0 o: 0 u: 0


In [3]:
#44
from mailmerge import MailMerge

doc = MailMerge("./Ex44_file/test.docx")
doc.merge(
    username="ddu",
    clazz="17计算机科学与技术"
)

doc.write("./Ex44_file/res.docx")


In [27]:
#45
from PIL import Image

fileName = "./Ex45_file/tuxiang.jpg"
img = Image.open(fileName)

imgSize = img.size

print(imgSize)



(471, 472)


In [28]:
#46
# 实现hashtable,指定在key位置存入data
class HashTable:
    def __init__(self):
        self.size = 11
        self.slots = [None] * self.size
        self.data = [None] * self.size

    def put(self, key, value):
        hashvalue = self.hashfunction(key, len(self.slots))
        if self.slots[hashvalue] is None:  # 如果slot内是空值，则存进去
            self.slots[hashvalue] = key
            self.data[hashvalue] = value
        else:  # slot内已有key
            if self.slots[hashvalue] == key:  # 如果已有值等于key，更新data
                self.data[hashvalue] = value
            else:  # 如果slot不等于key,找下一个为None的地方
                nextslot = self.rehash(hashvalue, len(self.slots))
                while self.slots[nextslot] is not None and self.slots[nextslot] != key:
                    nextslot = self.rehash(nextslot, len(self.slots))

                if self.slots[nextslot] is None:
                    self.slots[nextslot] = key
                    self.data[nextslot] = value
                else:
                    self.data[nextslot] = value

    def rehash(self, oldhash, size):
        return (oldhash + 1) % size

    # 散列函数
    def hashfunction(self, key, size):
        return key % size

    def get(self, key):
        startslot = self.hashfunction(key, len(self.slots))
        data = None
        found = False
        stop = False
        pos = startslot
        while pos is not None and not found and not stop:
            if self.slots[pos] == key:
                found = True
                data = self.data[pos]
            else:
                pos = self.rehash(pos, len(self.slots))
                # 回到了原点，表示找遍了没有找到
                if pos == startslot:
                    stop = True
        return data

    # 重载载 __getitem__ 和 __setitem__ 方法以允许使用 [] 访问
    def __getitem__(self, key):
        return self.get(key)

    def __setitem__(self, key, value):
        return self.put(key, value)


if __name__ == '__main__':
    H = HashTable()
    H[54] = "cat"
    H[26] = "dog"
    H[93] = "lion"
    H[17] = "tiger"
    H[77] = "bird"
    H[31] = "cow"
    H[44] = "goat"
    H[55] = "pig"
    H[20] = "chicken"

    print(H.slots)  # [77, 44, 55, 20, 26, 93, 17, None, None, 31, 54]
    print(H.data)  # ['bird', 'goat', 'pig', 'chicken', 'dog', 'lion', 'tiger', None, None, 'cow', 'cat']
    print(H[20])  # 'chicken'
    H[20] = 'duck'
    print(H[20])  # duck
    print(H[99])  # None



[77, 44, 55, 20, 26, 93, 17, None, None, 31, 54]
['bird', 'goat', 'pig', 'chicken', 'dog', 'lion', 'tiger', None, None, 'cow', 'cat']
chicken
duck
None
